name: Download and Commit MD File
on: push #pull_request
jobs:
  download-and-commit-md:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get list of new files
        id: newfiles
        run: |
          files=$(git diff --diff-filter=A --name-only ${{ github.event.before }} ${{ github.event.after }})
          echo "::set-output name=list::$(echo $files)"

      - name: Commit and Push MD File
        run: |
          # _posts 폴더에 새로운 파일이 있는지 확인
          MD_FILE=$(ls _posts | grep "$TODAY-test.md")
          if [ -n "$MD_FILE" ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add "_posts/$MD_FILE"
            git commit -m "Add new MD file from API response"
            git push
          else
            echo "No new .md file to commit"
          fi
      
      - name: Upload Files and Download MD
        run: |
          # 현재 날짜를 YYYY-MM-DD 형식으로 저장
          TODAY=$(date +'%Y-%m-%d')
          # API로부터 파일을 받아오고, 해당 파일명으로 _posts 폴더에 저장
          curl -X POST -H "Content-Type: multipart/form-data" -F "file=@yourfile" https://api.example.com/upload -o "_posts/$TODAY-test.md"
